"""add_version_table

Revision ID: 382931d97e22
Revises: e7e3bcd1d99a
Create Date: 2024-04-27 16:43:17.439340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382931d97e22'
down_revision: Union[str, None] = 'e7e3bcd1d99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('file_checksum', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('activation_words', sa.String(), nullable=True),
    sa.Column('custom_activation_words', sa.String(), nullable=True),
    sa.Column('blob', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('models', sa.Column('model_id', sa.String(length=50), nullable=True))
    op.add_column('models', sa.Column('request_url', sa.String(), nullable=True))
    op.drop_column('models', 'activation_words')
    op.drop_column('models', 'description')
    op.drop_column('models', 'checksum')
    op.drop_column('models', 'custom_activation_words')
    op.drop_column('models', 'source_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('custom_activation_words', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('checksum', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('activation_words', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('models', 'request_url')
    op.drop_column('models', 'model_id')
    op.drop_table('versions')
    # ### end Alembic commands ###
