"""remove model name length limit

Revision ID: 44a761199a9f
Revises: aa4906365aa3
Create Date: 2024-05-17 21:42:36.670124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a761199a9f'
down_revision: Union[str, None] = 'aa4906365aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('versions', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('versions', 'name',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('models', 'name',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
