"""remove files

Revision ID: 57e463d346e7
Revises: 382931d97e22
Create Date: 2024-04-27 20:14:07.693833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e463d346e7'
down_revision: Union[str, None] = '382931d97e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versions', 'file_checksum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('file_checksum', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
