"""change prompts fields

Revision ID: cd6d0d643623
Revises: 57e463d346e7
Create Date: 2024-05-04 21:52:22.729375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6d0d643623'
down_revision: Union[str, None] = '57e463d346e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('positive_prompts', sa.String(), nullable=True))
    op.add_column('versions', sa.Column('negative_prompts', sa.String(), nullable=True))
    op.add_column('versions', sa.Column('custom_positive_prompts', sa.String(), nullable=True))
    op.add_column('versions', sa.Column('custom_negative_prompts', sa.String(), nullable=True))
    op.drop_column('versions', 'activation_words')
    op.drop_column('versions', 'custom_activation_words')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('custom_activation_words', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('versions', sa.Column('activation_words', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('versions', 'custom_negative_prompts')
    op.drop_column('versions', 'custom_positive_prompts')
    op.drop_column('versions', 'negative_prompts')
    op.drop_column('versions', 'positive_prompts')
    # ### end Alembic commands ###
